-- USERS 테이블 생성
CREATE TABLE USERS (
  ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(50) NOT NULL,
  EMAIL VARCHAR2(100) NOT NULL UNIQUE,
  PASSWORD VARCHAR2(255) NOT NULL,
  CREATED_AT DATE NOT NULL DEFAULT SYSDATE,
  UPDATED_AT DATE NOT NULL DEFAULT SYSDATE
);

-- 시퀀스 생성
CREATE SEQUENCE USERS_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

-- 트리거 생성 (ID 자동 증가)
CREATE OR REPLACE TRIGGER USERS_BIR
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT USERS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

-- 인덱스 생성
CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);
CREATE INDEX IDX_USERS_CREATED_AT ON USERS(CREATED_AT DESC);

-- 예제 데이터 삽입
INSERT INTO USERS (NAME, EMAIL, PASSWORD)
VALUES ('관리자', 'admin@example.com', 'hashed_password_here');

COMMIT;
